### PR TITLE
Fix Buffer login

### PR DESCRIPTION
**Pull request by bonjourmauko**
Added the correct Buffer login.

### CODE REVIEW

**Comment by Morendil** [comment]
Is that typo on purpose ? 😂

**Comment by sandcha** [comment]
@maukoquiroga It didn't work when I tried it on `https://buffer.com/signin`. 🤔

**Review by sandcha — CHANGES_REQUESTED** [review]
See comments 🙂

**Review by sandcha — APPROVED** [review]
Thx 🙌

**Pull request merged**
